language: go
sudo: false
matrix:
  include:
    - go: 1.9
  allow_failures:
    - go: tip

before_install:
  - go get github.com/mitchellh/gox

install:
  - # skip

script:
  - go get -t -v ./...
#  - diff -u <(echo -n) <(gofmt -d .)
  - go vet ./...
  - go test -v -race ./...
  # Only build binaries from the latest Go release.
  - gox -os="linux darwin windows" -arch="amd64" -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...;

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $api_key
  file:
  - mssh_windows_amd64.exe
  - mssh_darwin_amd64
  - mssh_linux_amd64
  on:
    repo: pushthat/mssh
    tags: true
